### ISSUE TITLE
add package to ipm

### ISSUE THREAD

**Issue by skullbunnygalaxy** [q1701/inkdrop-copy-code-to-clipboard#1]
No install code listed in repo, and when I entered `ipm view inkdrop-copy-code-to-clipboard` I received the message:

> Requesting package failed: missing

**Comment by q1701** [comment]
The name of this plugin is [copy-code-to-clipboard](https://my.inkdrop.app/plugins/copy-code-to-clipboard).
Please try `ipm view copy-code-to-clipborad`. 😃
