### ISSUE TITLE
Copy Button Wrong Place When Code Block Scrolls Horizontally

### ISSUE THREAD

**Issue by StevanFreeborn** [q1701/inkdrop-copy-code-to-clipboard#13]
Copy button doesn't stay in the upper right hand corner of the code block when you scroll the code block horizontally.

![image](https://user-images.githubusercontent.com/65925598/167875470-dcb24f26-38a4-4633-ba38-e67f350e3c7c.png)

**Comment by q1701** [comment]
@StevanFreeborn Thank you for the report! I will try to fix it.

**Comment by q1701** [comment]
@StevanFreeborn I have fixed this behavior. Please update the plugin to v0.7.0.

**Comment by StevanFreeborn** [comment]
thanks @q1701 I appreciate the work!
