### ISSUE TITLE
The clipboard icon is missing in v5.6.0

### ISSUE THREAD

**Issue by craftzdog** [q1701/inkdrop-copy-code-to-clipboard#21]
v5.6.0 is currently in beta and will be released officially soon.
Font Awesome is no longer included in the app.
You can use the following code instead for now:

```html
<i class="icon clipboard outline"></i>
```

Reference: https://semantic-ui.com/elements/icon.html

**Comment by q1701** [comment]
Thanks for the report, Takuya. I have fixed it. Appreciate your consistent support!

**Comment by craftzdog** [comment]
Thank you, @q1701 🙌
