### ISSUE TITLE
Copy simple code

### ISSUE THREAD

**Issue by gustavotrott** [q1701/inkdrop-copy-code-to-clipboard#4]
I made some changes in the plugin to support copy simple codes as well, not only Block codes.
Are you interested in this functionallity? Then I can open a Pull Request.

![copy-code](https://user-images.githubusercontent.com/5660191/82851432-32299f80-9ed6-11ea-978a-29599c37d2bb.gif)

The copy icon is shown only on hover the code.
![image](https://user-images.githubusercontent.com/5660191/82850472-e75a5880-9ed2-11ea-816c-18813bd4a555.png)

**Comment by q1701** [comment]
What a great enhancement! 
Of course I will be waiting for your Pull Request.:star:

**Comment by q1701** [comment]
I have merged it. thanks.
